\set ON_ERROR_STOP on

create role anon;
create role authenticated;
create role service_role;

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null,
    sector text,
    sales_id bigint
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    background text,
    avatar jsonb,
    first_seen timestamptz,
    last_seen timestamptz,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null
);

insert into public.companies (name, sector)
values ('Örebro kommun', 'Municipal & Government');

insert into public.contacts (
    first_name,
    last_name,
    email_jsonb,
    phone_jsonb,
    has_newsletter,
    company_id
)
values (
    'Befintlig',
    'Prenumerant',
    '[{"email":"legacy@example.se","type":"Work"}]'::jsonb,
    '[]'::jsonb,
    true,
    1
);

\ir ../migrations/20260908090000_organizations_newsletter_mcp.sql

-- Existing active records must not receive invented consent dates.
do $$
begin
    if (select organization_type from public.companies where id = 1)
        <> 'municipality' then
        raise exception 'Existing municipality was not classified correctly';
    end if;

    if (select newsletter_subscribed_at from public.contacts where id = 1)
        is not null then
        raise exception 'Migration invented a historical subscription date';
    end if;
end;
$$;

-- New active subscribers get a start timestamp from the trigger.
insert into public.contacts (
    first_name,
    last_name,
    email_jsonb,
    phone_jsonb,
    has_newsletter,
    company_id
)
values (
    'Ny',
    'Prenumerant',
    '[{"email":"new@example.se","type":"Work"}]'::jsonb,
    '[]'::jsonb,
    true,
    1
);

do $$
begin
    if (select newsletter_subscribed_at from public.contacts where id = 2)
        is null then
        raise exception 'New active subscriber did not receive a start date';
    end if;
end;
$$;

-- Unsubscription retains the start date and sets an end date.
update public.contacts set has_newsletter = false where id = 2;

do $$
begin
    if (select newsletter_subscribed_at from public.contacts where id = 2)
        is null then
        raise exception 'Unsubscription removed the start date';
    end if;

    if (select newsletter_unsubscribed_at from public.contacts where id = 2)
        is null then
        raise exception 'Unsubscription did not set the end date';
    end if;
end;
$$;

-- Re-subscription sets a fresh start and clears the end date.
update public.contacts set has_newsletter = true where id = 2;

do $$
begin
    if (select newsletter_unsubscribed_at from public.contacts where id = 2)
        is not null then
        raise exception 'Re-subscription did not clear the end date';
    end if;
end;
$$;

-- The summary view must expose both lifecycle fields.
select newsletter_subscribed_at, newsletter_unsubscribed_at
from public.contacts_summary
where id = 2;
