-- ============================================================================
-- SALES AGENT INTEGRATION
-- ============================================================================
-- Adds tables and configuration to support the autonomous Manus sales agent.
--
-- New tables:
--   mail_templates  — Stores Markdown email/RFI templates for outreach
--   agent_config    — Key-value configuration for agent behavior
--
-- Changes to existing tables:
--   (none — task types and contact statuses are frontend-only config)
--
-- See: atomic-crm-frontend-changes.md for corresponding frontend changes
-- ============================================================================

-- 1. Mail Templates
-- Stores reusable Markdown templates for email bodies and RFI documents.
-- The agent fetches the appropriate template based on prospect type.
CREATE TABLE IF NOT EXISTS public.mail_templates (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    description text,
    subject text NOT NULL,
    body_markdown text NOT NULL,
    template_type text NOT NULL DEFAULT 'email'
        CHECK (template_type IN ('email', 'rfi', 'linkedin', 'followup')),
    target_sector text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.mail_templates IS 'Reusable Markdown templates for sales outreach (email, RFI, LinkedIn).';
COMMENT ON COLUMN public.mail_templates.name IS 'Unique template identifier, e.g. municipality_rfi_v1';
COMMENT ON COLUMN public.mail_templates.template_type IS 'Template category: email, rfi, linkedin, or followup';
COMMENT ON COLUMN public.mail_templates.target_sector IS 'Which company sector this template targets, or NULL for universal';

-- 2. Agent Config
-- Key-value store for agent settings. Allows dynamic behavior changes
-- without redeploying the agent.
CREATE TABLE IF NOT EXISTS public.agent_config (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key text NOT NULL UNIQUE,
    value text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.agent_config IS 'Key-value configuration for the autonomous sales agent.';

-- 3. RLS Policies
-- Both tables are read-only for authenticated users.
-- The agent uses the service role key to write.
ALTER TABLE public.mail_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access for authenticated users"
    ON public.mail_templates FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Allow read access for authenticated users"
    ON public.agent_config FOR SELECT
    USING (auth.role() = 'authenticated');

-- Allow anon role to read (same pattern as other CRM tables)
CREATE POLICY "Allow anon read access"
    ON public.mail_templates FOR SELECT
    USING (auth.role() = 'anon');

CREATE POLICY "Allow anon read access"
    ON public.agent_config FOR SELECT
    USING (auth.role() = 'anon');

-- 4. Seed initial configuration
INSERT INTO public.agent_config (key, value, description) VALUES
    ('default_sales_id', '7', 'Default sales_id for pipeline-created records (Johan Lido)'),
    ('municipality_rfi_template', 'municipality_rfi_v1', 'Template name for municipality RFI outreach'),
    ('private_sector_email_template', 'private_sector_intro_v1', 'Template name for private sector email outreach'),
    ('followup_days', '7', 'Number of days before creating a follow-up task'),
    ('max_outreach_attempts', '3', 'Maximum number of outreach attempts before pausing'),
    ('onepager_generation', 'true', 'Whether to generate HTML onepagers for new prospects')
ON CONFLICT (key) DO NOTHING;

-- 5. Seed initial mail templates
INSERT INTO public.mail_templates (name, description, subject, body_markdown, template_type, target_sector) VALUES
    (
        'municipality_rfi_v1',
        'RFI Marknadsdialog for municipalities — references Sveriges digitaliseringsstrategi 2025-2030 and AI-strategi 2026',
        'Marknadsdialog: Digital inkludering och Sveriges digitala strategi — {{RECIPIENT}}',
        '# Marknadsdialog: Digital inkludering och efterlevnad av Sveriges digitaliseringsstrategi 2025–2030

**Dokumenttyp:** Marknadsdialog
**Datum:** {{DATE}}
**Mottagare:** {{RECIPIENT}}

---

## Bakgrund

I maj 2025 antog regeringen Sveriges digitaliseringsstrategi 2025–2030 med målet att Sverige ska vara bäst i världen på att använda digitaliseringens möjligheter. I februari 2026 kompletterades detta med Sveriges första nationella AI-strategi.

Civisto arbetar med att bygga nationell infrastruktur för medborgarrapportering som gör det möjligt för alla invånare — oavsett digital vana eller tillgång till e-legitimation — att enkelt rapportera fel och brister i sin närmiljö.

Vi vänder oss till {{RECIPIENT}} med denna marknadsdialog för att förstå hur ni arbetar med dessa frågor idag.

---

## Frågor

### A. Digital inkludering och tillgänglighet

1. Hur kan medborgare utan BankID eller e-legitimation rapportera fel idag?
2. Finns det alternativa kanaler för personer med funktionsnedsättning?
3. Hur säkerställer ni att alla invånare kan nå er — oavsett digital vana?

### B. Medborgarnytta och administration

4. Hur hanteras inkommande felanmälningar idag — webbformulär, app, telefon, e-post?
5. Hur stor andel av ärendena kräver manuell komplettering eller omstyrning?
6. Finns det en samlad bild av alla inkommande ärenden och deras status?

### C. Datadriven förvaltning och AI

7. Hur planerar ni att möta AI-strategins mål om världsledande AI i offentlig förvaltning?
8. Finns det pågående projekt kring AI-stödd ärendehantering eller automatiserad kategorisering?
9. Hur ser ni på möjligheten att använda AI för att förbättra servicen till medborgarna?

### D. Samverkan och interoperabilitet

10. Använder ni öppna standarder för ärendehantering?
11. Finns det intresse av att delta i en nationell infrastruktur för medborgarrapportering?

---

**Kontakt:** Johan Lido, johan@civisto.com, 070-556 93 37
**Webb:** civisto.com
**Org.nr:** 559571-7934',
        'rfi',
        'Municipal & Government'
    ),
    (
        'private_sector_intro_v1',
        'Initial outreach email for private sector companies (property management, facility management)',
        'Smartare felanmälan för {{COMPANY_NAME}} — Civisto',
        'Hej {{CONTACT_NAME}},

Jag heter Johan och arbetar med Civisto — en plattform som hjälper fastighetsägare att effektivisera felanmälan och drifthantering med hjälp av QR-koder och AI.

Jag kontaktar dig eftersom {{COMPANY_NAME}} förvaltar ett betydande fastighetsbestånd och jag tror att ni kan ha nytta av ett enklare sätt att ta emot och hantera felanmälningar från hyresgäster.

**Kort om Civisto:**
- Hyresgästen scannar en QR-kod och beskriver problemet — klart på 7 sekunder
- AI kategoriserar och prioriterar automatiskt
- Rätt team får ärendet direkt, med all kontext
- Ingen app att ladda ner, inget konto att skapa

Vi erbjuder en 6 månaders kostnadsfri testperiod med full funktionalitet.

Skulle det passa med ett kort samtal nästa vecka för att diskutera hur detta kan se ut för er?

Med vänliga hälsningar,
Johan Lido
Civisto
johan@civisto.com | 070-556 93 37 | civisto.com',
        'email',
        'Real Estate & Property Management'
    ),
    (
        'municipality_intro_email_v1',
        'Introductory email sent together with the RFI PDF to municipalities',
        'Marknadsdialog om digital inkludering — {{RECIPIENT}}',
        'Hej {{CONTACT_NAME}},

Jag heter Johan och arbetar med Civisto, en plattform för medborgarrapportering som gör det möjligt för alla invånare att enkelt rapportera fel och brister — utan krav på BankID eller app.

Med anledning av Sveriges digitaliseringsstrategi 2025–2030 och den nya AI-strategin från februari 2026 vänder jag mig till {{RECIPIENT}} med en kort marknadsdialog (bifogad PDF).

Syftet är att förstå hur ni arbetar med felanmälan och digital inkludering idag, och om det finns intresse av att utforska hur AI-stödd rapportering kan stärka er medborgarservice.

Jag ringer gärna vecka {{FOLLOW_UP_WEEK}} för ett kort samtal.

Med vänliga hälsningar,
Johan Lido
Civisto
johan@civisto.com | 070-556 93 37 | civisto.com',
        'email',
        'Municipal & Government'
    )
ON CONFLICT (name) DO NOTHING;
